-- Seed the first editorial expansion of the resource library.
-- All resources remain drafts until their complete text has been reviewed in admin preview.

with seed_resources as (
  select *
  from jsonb_to_recordset($$[
    {
      "title": "Fra strategi til konkret lederpraksis",
      "slug": "fra-strategi-til-konkret-lederpraksis",
      "type": "exercise",
      "phase": "experiment",
      "estimated_duration": 15,
      "difficulty": "medium",
      "intended_outcome": "Oversette én strategisk prioritering til to konkrete lederhandlinger, én nedprioritering og et tydelig tegn på fremgang.",
      "best_used_when": ["en strategisk prioritering er forstått, men ikke synlig i praksis", "lederen trenger å avgrense hva prioriteringen betyr i egen rolle", "dagens vaner trekker oppmerksomheten bort fra det viktigste"],
      "not_for": ["strategien eller mandatet er fortsatt uavklart", "situasjonen krever en bred strategiprosess fremfor et individuelt ledergrep"],
      "coach_guidance": "Hold arbeidet på nivået observerbar lederatferd. Hjelp lederen å velge få handlinger og én reell nedprioritering. Ressursen skal ikke bli en ny aktivitetsliste.",
      "client_intro": "En strategisk prioritering får først verdi når den påvirker valgene du tar i arbeidshverdagen. Denne øvelsen hjelper deg å gjøre én prioritering synlig i egen lederpraksis.",
      "suggested_coach_note": "Bruk denne på én strategisk prioritering som er viktig nå. Målet er å gjøre den synlig i konkrete ledervalg de neste to ukene.",
      "default_context_types": ["focus_area", "experiment", "session"],
      "content_json": [
        { "type": "intro", "content": "Velg én prioritering. Arbeid med hva du faktisk skal gjøre annerledes, ikke med å gjengi strategien mer presist." },
        { "type": "text", "heading": "1. Velg prioriteringen", "content": "Skriv prioriteringen med egne ord og beskriv hvilken forskjell den skal gjøre i din del av virksomheten." },
        { "type": "worksheet", "fields": ["Hvilken strategisk prioritering arbeider du med?", "Hva skal bli annerledes dersom dere lykkes?"] },
        { "type": "text", "heading": "2. Gjør den synlig", "content": "Beskriv hva medarbeidere eller kolleger skal kunne se at du gjør annerledes." },
        { "type": "worksheet", "fields": ["Hvilke to lederhandlinger skal du gjøre oftere?", "Hva skal du gjøre mindre av eller slutte med?", "Hvem vil merke endringen først?"] },
        { "type": "text", "heading": "3. Bestem når du skal handle", "content": "Knytt den nye praksisen til en bestemt situasjon. En konkret utløsende situasjon gjør det lettere å handle når arbeidshverdagen tar over." },
        { "type": "worksheet", "fields": ["Når denne situasjonen oppstår ...", "... skal jeg gjøre dette", "Hvilket tegn skal du se etter etter to uker?"] },
        { "type": "reflection_questions", "heading": "Tenk gjennom", "questions": ["Hvilket av dagens ledervalg trekker i motsatt retning?", "Hva vil gjøre det lett å falle tilbake til gammel praksis?", "Hva trenger du å beskytte i kalenderen eller arbeidsformen?"] }
      ],
      "reflection_prompts": [],
      "next_step_prompt": "Velg den første konkrete situasjonen der du skal prøve den nye lederhandlingen, og legg den inn i kalenderen.",
      "basis": "Målsettingsteori og implementeringsintensjoner. Locke og Latham (2002); Gollwitzer (1999)."
    },
    {
      "title": "Forstå motstand før du leder endring",
      "slug": "forsta-motstand-for-du-leder-endring",
      "type": "reflection",
      "phase": "observation",
      "estimated_duration": 15,
      "difficulty": "medium",
      "intended_outcome": "Forstå reaksjoner på endring mer presist og velge et bedre begrunnet neste grep.",
      "best_used_when": ["en endring møter lav oppslutning eller tydelige innvendinger", "fremdriften stopper uten at årsaken er klar", "lederen står i fare for å forklare reaksjonen som manglende vilje"],
      "not_for": ["formelle medvirknings- eller arbeidsmiljøprosesser", "situasjoner der kritikk eller varsling krever særskilt håndtering", "bruk for å stemple ansatte som endringsuvillige"],
      "coach_guidance": "Be lederen holde observasjon og fortolkning fra hverandre. Motstand kan inneholde viktig informasjon om innhold, prosess, kontekst eller opplevde konsekvenser. Ikke hjelp lederen med å selge hardere før situasjonen er bedre forstått.",
      "client_intro": "Stillhet, forsinkelse og innvendinger kan ha flere forklaringer. Før du velger neste grep, trenger du å forstå hva reaksjonen faktisk kan handle om og hva du fortsatt ikke vet.",
      "suggested_coach_note": "Bruk øvelsen på én konkret endring der reaksjonene er vanskelige å forstå. Skill tydelig mellom det du vet og det du antar.",
      "default_context_types": ["session", "focus_area", "reflection"],
      "content_json": [
        { "type": "intro", "content": "Reaksjoner på endring er ikke én ting. De kan handle om selve løsningen, måten endringen gjennomføres på, lokal historie eller hva mennesker opplever å vinne og tape." },
        { "type": "model_cards", "heading": "Fire steder å lete", "cards": [{ "title": "Innhold", "body": "Er selve endringen forståelig, gjennomførbar og godt begrunnet?" }, { "title": "Prosess", "body": "Hvordan er mennesker informert, involvert og behandlet underveis?" }, { "title": "Kontekst", "body": "Hvilke tidligere erfaringer, relasjoner eller lokale forhold preger reaksjonen?" }, { "title": "Nytte og tap", "body": "Hva kan mennesker oppleve å få, miste eller risikere?" }] },
        { "type": "text", "heading": "1. Beskriv det du observerer", "content": "Beskriv konkret atferd uten å legge motiv eller personlighet inn i beskrivelsen." },
        { "type": "worksheet", "fields": ["Hva ser eller hører du faktisk?", "Hva er din foreløpige forklaring?", "Hva vet du ikke ennå?"] },
        { "type": "text", "heading": "2. Undersøk før du påvirker", "content": "Vurder de fire mulige forklaringsstedene og bestem hvilken informasjon du trenger fra dem som berøres." },
        { "type": "worksheet", "fields": ["Hvilken legitim bekymring kan du ha undervurdert?", "Hvilke to spørsmål kan gi bedre informasjon?", "Hva må stå fast?", "Hva er du villig til å justere?"] },
        { "type": "reflection_questions", "heading": "Tenk gjennom", "questions": ["Hva ved din egen fremgangsmåte kan bidra til reaksjonen?", "Hvem trenger du å lytte til før du bestemmer neste grep?", "Hvordan vil du vise hva du har tatt inn, også når beslutningen står fast?"] }
      ],
      "reflection_prompts": [],
      "next_step_prompt": "Ta én undersøkende samtale før du velger neste kommunikasjons- eller gjennomføringsgrep.",
      "basis": "Forskning på mottakerreaksjoner ved organisatorisk endring. Oreg, Vakola og Armenakis (2011)."
    },
    {
      "title": "Definer problemet før du velger løsning",
      "slug": "definer-problemet-for-du-velger-losning",
      "type": "worksheet",
      "phase": "focus",
      "estimated_duration": 15,
      "difficulty": "medium",
      "intended_outcome": "Formulere en foreløpig problemdefinisjon som kan undersøkes uten at en foretrukket løsning er bygget inn i den.",
      "best_used_when": ["tiltak diskuteres før problemet er tydelig", "symptomer og årsaker blandes sammen", "gruppen har samlet seg raskt om én løsning"],
      "not_for": ["akutte situasjoner der umiddelbar handling er nødvendig", "problemdefinisjonen brukes til å forsinke en nødvendig beslutning"],
      "coach_guidance": "Stopp lederen når løsningen sniker seg inn i problemformuleringen. Målet er ikke perfekt analyse, men en tydeligere foreløpig forståelse som kan testes mot flere perspektiver og data.",
      "client_intro": "Når en løsning kommer tidlig, er det lett å beskrive problemet slik at løsningen virker selvsagt. Denne øvelsen hjelper deg å formulere problemet før du bestemmer tiltaket.",
      "suggested_coach_note": "Bruk denne på et problem der dere allerede diskuterer tiltak. Se om problemformuleringen fortsatt holder når løsningen tas ut av setningen.",
      "default_context_types": ["focus_area", "session", "reflection"],
      "content_json": [
        { "type": "intro", "content": "En problemdefinisjon er foreløpig. Den skal hjelpe deg å stille bedre spørsmål og kunne endres når ny informasjon kommer." },
        { "type": "callout", "tone": "note", "heading": "Sjekk formuleringen", "content": "Hvis problemet formuleres som «vi mangler et nytt system», har du allerede valgt løsning. Beskriv først hva som ikke fungerer, for hvem og med hvilken virkning." },
        { "type": "text", "heading": "1. Beskriv situasjonen", "content": "Start med det som kan observeres, og beskriv gapet mellom dagens og ønsket situasjon." },
        { "type": "worksheet", "fields": ["Hva skjer faktisk? Bruk konkrete observasjoner eller data.", "Hva skulle skjedd i stedet?", "Hvem opplever problemet, og hvem gjør det ikke?"] },
        { "type": "text", "heading": "2. Skill delene", "content": "Et symptom er det du ser. En mulig årsak er en forklaring som må undersøkes. En konsekvens er det situasjonen fører til." },
        { "type": "worksheet", "fields": ["Hva er symptomet?", "Hvilke to mulige årsaker kan passe?", "Hva er de viktigste konsekvensene?", "Hvilke rammer eller begrensninger må tas hensyn til?"] },
        { "type": "text", "heading": "3. Formuler problemet", "content": "Skriv en kort formulering som beskriver gapet, hvem det gjelder og hvorfor det betyr noe, uten å nevne en bestemt løsning." },
        { "type": "worksheet", "fields": ["Vår foreløpige problemdefinisjon", "Hva må vi undersøke før vi velger løsning?"] },
        { "type": "reflection_questions", "heading": "Tenk gjennom", "questions": ["Hvilken løsning har du allerede forelsket deg i?", "Hvem ser situasjonen fra en annen vinkel?", "Hva ville fått deg til å endre problemdefinisjonen?"] }
      ],
      "reflection_prompts": [],
      "next_step_prompt": "Test problemdefinisjonen med én person som er berørt og én som ser situasjonen utenfra.",
      "basis": "Problemkonstruksjon i uklare og dårlig definerte problemområder. Getzels (1979); Mumford, Reiter-Palmon og Redmond (1994)."
    },
    {
      "title": "Test antakelsene bak beslutningen",
      "slug": "test-antakelsene-bak-beslutningen",
      "type": "exercise",
      "phase": "focus",
      "estimated_duration": 12,
      "difficulty": "medium",
      "intended_outcome": "Identifisere og undersøke minst én kritisk og usikker antakelse før en viktig beslutning eller større investering.",
      "best_used_when": ["en beslutning hviler på flere usikre premisser", "gruppen har samlet seg raskt om én forklaring", "kostnaden ved å oppdage en feil sent er høy"],
      "not_for": ["beslutninger der forsinkelse skaper større risiko enn manglende informasjon", "bruk for å skape kunstig sikkerhet eller fjerne all usikkerhet"],
      "coach_guidance": "Hjelp lederen å skille mellom fakta og forhold som må være sanne for at anbefalingen skal være god. Se etter en liten og forsvarlig test. Ikke gjør øvelsen til en generell liste over alle tenkelige risikoer.",
      "client_intro": "Viktige beslutninger bygger ofte på forhold vi antar er sanne. Denne øvelsen hjelper deg å finne den mest kritiske antakelsen og lete etter informasjon som faktisk kan utfordre den.",
      "suggested_coach_note": "Bruk denne før du låser en viktig beslutning. Velg særlig en antakelse som både er avgjørende og usikker.",
      "default_context_types": ["focus_area", "experiment", "session"],
      "content_json": [
        { "type": "intro", "content": "Målet er ikke å fjerne usikkerhet. Målet er å oppdage om beslutningen hviler på et svakt premiss mens det fortsatt er mulig å justere." },
        { "type": "text", "heading": "1. Finn antakelsene", "content": "Skriv beslutningen eller anbefalingen i én setning. List deretter forholdene som må være sanne for at den skal være god." },
        { "type": "worksheet", "fields": ["Beslutningen eller anbefalingen", "Antakelse 1", "Antakelse 2", "Antakelse 3", "Hvilken antakelse er både viktigst og mest usikker?"] },
        { "type": "text", "heading": "2. Let etter motinformasjon", "content": "Beskriv hva du ville forventet å se dersom den viktigste antakelsen er feil, og hvor du kan hente relevant informasjon." },
        { "type": "worksheet", "fields": ["Hva ville tyde på at antakelsen er feil?", "Hvilken informasjon ville fått deg til å skifte mening?", "Hva er den raskeste forsvarlige testen?", "Hvem kan se noe dere andre overser?"] },
        { "type": "text", "heading": "3. Gjør en føranalyse", "content": "Tenk at beslutningen er gjennomført og har mislyktes. Beskriv den mest sannsynlige forklaringen, ikke den mest dramatiske." },
        { "type": "worksheet", "fields": ["Den mest sannsynlige grunnen til at dette mislyktes", "Hva kan vi gjøre nå for å undersøke eller redusere denne risikoen?"] },
        { "type": "reflection_questions", "heading": "Tenk gjennom", "questions": ["Hva er kostnaden ved å teste antakelsen nå?", "Hva er kostnaden ved å oppdage feilen senere?", "Er dere åpne for å endre beslutningen, eller leter dere bare etter bekreftelse?"] }
      ],
      "reflection_prompts": [],
      "next_step_prompt": "Gjennomfør én liten test eller hent inn ett tydelig motperspektiv før beslutningen låses.",
      "basis": "Forskning på hypotesetesting og positiv teststrategi, supplert med premortem som praktisk arbeidsform. Klayman og Ha (1987); Klein (2007)."
    },
    {
      "title": "Hva bygger og bryter ned tillit?",
      "slug": "hva-bygger-og-bryter-ned-tillit",
      "type": "framework",
      "phase": "reflection",
      "estimated_duration": 15,
      "difficulty": "medium",
      "intended_outcome": "Forstå hva tilliten i én konkret relasjon hviler på og velge én synlig handling som kan gjøre samarbeidet mer forutsigbart.",
      "best_used_when": ["samarbeidet er preget av tilbakeholdenhet eller ekstra kontroll", "partene viser lav vilje til å være avhengige av hverandre", "det er uklart hva mistilliten gjelder"],
      "not_for": ["varsling, trakassering eller alvorlige arbeidsmiljøsaker", "økonomiske misligheter eller andre forhold som krever formell håndtering", "bruk for å vurdere den andre personens karakter"],
      "coach_guidance": "Hold analysen på konkrete handlinger og én relasjon. Be lederen lete etter både støtte og moteksempler til egen vurdering. Tillit handler om å akseptere en viss sårbarhet, ikke om at den andre skal være enig eller ukritisk.",
      "client_intro": "Tillit blir synlig når vi må være avhengige av andre. Denne modellen hjelper deg å undersøke hva som gjør en konkret relasjon trygg eller utrygg, og hva du selv kan gjøre mer troverdig.",
      "suggested_coach_note": "Velg én viktig relasjon der samarbeidet krever tillit, men er preget av tilbakeholdenhet eller ekstra kontroll.",
      "default_context_types": ["focus_area", "session", "reflection"],
      "content_json": [
        { "type": "intro", "content": "Tillit handler ikke bare om god kjemi. Den blir viktig når du må gjøre deg avhengig av den andres vurdering, handling eller ord." },
        { "type": "model_cards", "heading": "Tre sider ved troverdighet", "cards": [{ "title": "Dyktighet", "body": "Har personen relevant evne, kunnskap og dømmekraft i denne situasjonen?" }, { "title": "Velvilje", "body": "Tar personen rimelig hensyn til den andres interesser, også når interessene ikke er helt like?" }, { "title": "Integritet", "body": "Er det samsvar mellom det personen sier, gjør og står for over tid?" }] },
        { "type": "text", "heading": "1. Velg relasjonen", "content": "Velg én relasjon og én konkret situasjon der dere trenger å kunne stole på hverandre." },
        { "type": "worksheet", "fields": ["Hvilken relasjon og situasjon gjelder det?", "Hva må den andre være villig til å overlate eller risikere?", "Hva må du selv være villig til å overlate eller risikere?"] },
        { "type": "text", "heading": "2. Undersøk din egen troverdighet", "content": "Vurder hva den andre faktisk har sett fra deg. Bruk konkrete eksempler fremfor generelle egenskaper." },
        { "type": "worksheet", "fields": ["Hva har du gjort som viser dyktighet i denne situasjonen?", "Hva viser at du tar rimelig hensyn til den andres interesser?", "Hvor er det tydelig samsvar mellom ord og handling?", "Hvilket moteksempel bør du ta på alvor?"] },
        { "type": "reflection_questions", "heading": "Tenk gjennom", "questions": ["Hvilken forklaring har du på den andres tilbakeholdenhet?", "Hva kan du gjøre som er synlig og etterprøvbart, ikke bare betryggende ord?", "Hva trenger du å spørre den andre om før du konkluderer?"] }
      ],
      "reflection_prompts": [],
      "next_step_prompt": "Velg én konkret handling som kan gjøre deg mer forutsigbar eller troverdig i relasjonen, og følg den opp over tid.",
      "basis": "Organisatorisk tillit og tillit til ledere. Mayer, Davis og Schoorman (1995); Dirks og Ferrin (2002)."
    },
    {
      "title": "Gjenopprett tillit etter et brudd",
      "slug": "gjenopprett-tillit-etter-et-brudd",
      "type": "guided_session",
      "phase": "adjustment",
      "estimated_duration": 20,
      "difficulty": "advanced",
      "intended_outcome": "Beskrive hendelse og virkning presist, ta ansvar for egen del og forberede en reparasjon som kan vurderes gjennom handling over tid.",
      "best_used_when": ["lederen selv har bidratt til et konkret tillitsbrudd", "en beklagelse alene ikke er tilstrekkelig", "relasjonen fortsatt er viktig og reparasjon er forsvarlig"],
      "not_for": ["pågående skade eller alvorlige arbeidsmiljøsaker", "situasjoner som krever juridisk, HR-faglig eller formell håndtering", "uenighet om faktum der lederen presses til å innrømme noe som ikke er avklart"],
      "coach_guidance": "Vurder først om coaching er riktig arena. Hjelp lederen å skille hensikt fra virkning og ansvar fra selvfordømmelse. Ikke gjør ressursen til et manus for rask tilgivelse. Reell reparasjon krever relevant handling og tid.",
      "client_intro": "Når egen handling har svekket tillit, er gode intensjoner og en rask beklagelse sjelden nok alene. Denne øvelsen hjelper deg å forberede ansvar, reparasjon og oppfølging på en ryddig måte.",
      "suggested_coach_note": "Bruk denne bare dersom du selv har et tydelig ansvar i hendelsen og relasjonen kan håndteres forsvarlig gjennom en direkte samtale.",
      "default_context_types": ["session", "reflection", "focus_area"],
      "content_json": [
        { "type": "callout", "tone": "note", "heading": "Før du begynner", "content": "Denne øvelsen er ikke laget for pågående skade, varsling eller alvorlige arbeidsmiljøsaker. Slike forhold må håndteres gjennom riktige formelle og faglige prosesser." },
        { "type": "intro", "content": "Målet er ikke å få den andre til å tilgi. Målet er å ta presist ansvar, forstå virkningen og gjøre reparasjonen etterprøvbar." },
        { "type": "text", "heading": "1. Beskriv bruddet", "content": "Skill det som skjedde fra hva du ønsket skulle skje. Den andre parten kan ha opplevd en annen virkning enn du hadde til hensikt." },
        { "type": "worksheet", "fields": ["Hva skjedde konkret?", "Hva var din hensikt?", "Hvilken virkning kan handlingen ha hatt?", "Hva kan den andre ha mistet, risikert eller blitt usikker på?"] },
        { "type": "text", "heading": "2. Ta ansvar", "content": "Avklar hvilken del du faktisk eier. Unngå forbehold som gjør den andre ansvarlig for din erkjennelse." },
        { "type": "worksheet", "fields": ["Hva tar du ansvar for?", "Gjelder bruddet først og fremst dyktighet, hensyn til den andre, integritet eller flere forhold?", "Hvordan kan du erkjenne dette kort og presist?"] },
        { "type": "text", "heading": "3. Forbered reparasjonen", "content": "Ord må følges av en handling som svarer på det som faktisk ble svekket. Den andre parten må få påvirke hva som er relevant." },
        { "type": "worksheet", "fields": ["Hva trenger du å høre fra den andre før du foreslår løsning?", "Hva kan du med rimelighet reparere?", "Hvilken konkret atferd må endres?", "Når og hvordan skal dere følge opp?"] },
        { "type": "reflection_questions", "heading": "Tenk gjennom", "questions": ["Hva kan du ikke kreve tilgivelse for?", "Hvilken ny atferd må være stabil over tid for at ordene skal være troverdige?", "Er du klar til å høre virkningen uten å korrigere den andres opplevelse?"] }
      ],
      "reflection_prompts": [],
      "next_step_prompt": "Forbered en kort åpning, men la den andre parten beskrive virkningen før du foreslår reparasjonen.",
      "basis": "Forskning på organisatorisk tillit og reparasjon etter kompetanse- og integritetsrelaterte tillitsbrudd. Mayer, Davis og Schoorman (1995); Kim, Ferrin, Cooper og Dirks (2004)."
    },
    {
      "title": "Skap gjennomslag uten formell myndighet",
      "slug": "skap-gjennomslag-uten-formell-myndighet",
      "type": "exercise",
      "phase": "experiment",
      "estimated_duration": 15,
      "difficulty": "medium",
      "intended_outcome": "Velge en situasjonstilpasset påvirkningsform og formulere en tydelig, rimelig forespørsel til en aktør utenfor egen styringslinje.",
      "best_used_when": ["lederen trenger støtte fra en kollega, fagperson eller overordnet", "formell myndighet ikke kan brukes", "gode argumenter alene ikke har gitt gjennomslag"],
      "not_for": ["bruk for å skjule interesser eller omgå beslutningsprosesser", "situasjoner der den andre parten ikke kan gi reelt samtykke", "påvirkning som bygger på press, villedning eller utilbørlig gjengjeldelse"],
      "coach_guidance": "Be lederen starte med påvirkningsmålet og den andres situasjon, ikke med taktikken. Påvirkning skal være åpen om interesser og gi rom for et reelt nei eller et bedre forslag.",
      "client_intro": "Du trenger ofte bidrag fra mennesker du ikke kan instruere. Denne øvelsen hjelper deg å forberede én påvirkningssamtale uten å lene deg på posisjon eller gjenta det samme argumentet sterkere.",
      "suggested_coach_note": "Velg én kommende samtale med en person du er avhengig av, men ikke kan instruere. Forbered en tydelig forespørsel og hva du trenger å forstå først.",
      "default_context_types": ["focus_area", "experiment", "session"],
      "content_json": [
        { "type": "intro", "content": "Påvirkning uten formell myndighet starter med å forstå hva du trenger, hvorfor den andre parten skulle bidra, og hva slags innflytelse du faktisk har i relasjonen." },
        { "type": "model_cards", "heading": "Mulige kilder til innflytelse", "cards": [{ "title": "Kunnskap", "body": "Du har relevant innsikt eller informasjon som forbedrer saken." }, { "title": "Troverdighet", "body": "Dine vurderinger har vist seg pålitelige i denne typen situasjon." }, { "title": "Relasjon", "body": "Dere har bygget respekt og en historie med ryddig samarbeid." }, { "title": "Gjensidighet", "body": "Dere kan bidra til hverandres legitime mål uten å gjøre det til skjult byttehandel." }] },
        { "type": "text", "heading": "1. Avklar målet", "content": "Bestem hva du konkret ønsker at personen skal forstå, bidra med eller beslutte." },
        { "type": "worksheet", "fields": ["Hvem ønsker du å påvirke?", "Hva ønsker du konkret fra personen?", "Hvorfor trenger saken akkurat denne personens bidrag?"] },
        { "type": "text", "heading": "2. Forstå den andres situasjon", "content": "Vurder mål, risiko og handlingsrom fra den andres ståsted før du velger argumentasjon." },
        { "type": "worksheet", "fields": ["Hva kan saken bety for den andres mål?", "Hvilken bekymring eller kostnad er rimelig?", "Hva trenger du å spørre om før du argumenterer?", "Hvilken kilde til innflytelse kan du bruke åpent og redelig?"] },
        { "type": "text", "heading": "3. Formuler forespørselen", "content": "Lag en forespørsel som er tydelig nok til at den andre kan svare ja, nei eller foreslå et alternativ." },
        { "type": "worksheet", "fields": ["Min konkrete forespørsel", "Hvordan vil jeg møte en legitim motforestilling?", "Hva er et mindre neste steg dersom full støtte ikke er mulig nå?"] },
        { "type": "reflection_questions", "heading": "Tenk gjennom", "questions": ["Hvorfor skulle den andre prioritere dette nå?", "Hva kan du lære dersom personen er uenig?", "Er du mer opptatt av gjennomslag enn av kvaliteten på beslutningen?"] }
      ],
      "reflection_prompts": [],
      "next_step_prompt": "Gjennomfør samtalen med én tydelig forespørsel og minst ett spørsmål før du argumenterer.",
      "basis": "Kilder til sosial makt og situasjonstilpassede påvirkningstaktikker. French og Raven (1959); Yukl, Guinan og Sottolano (1995)."
    },
    {
      "title": "Fra interessentkart til påvirkningsgrep",
      "slug": "fra-interessentkart-til-pavirkningsgrep",
      "type": "worksheet",
      "phase": "focus",
      "estimated_duration": 20,
      "difficulty": "medium",
      "intended_outcome": "Prioritere tre interessenter, velge en begrunnet tilnærming til hver og bestemme hvem som bør involveres først.",
      "best_used_when": ["interessentene allerede er kartlagt", "lederen mangler en plan for involvering og rekkefølge", "viktige aktører ofte kommer for sent inn"],
      "not_for": ["bruk for å spille aktører mot hverandre", "planlegging som skjuler relevant informasjon", "situasjoner der formelle konsultasjons- eller medvirkningskrav styrer prosessen"],
      "coach_guidance": "Denne ressursen skal følge etter Interessentkart og ikke gjenta kartleggingen. Utfordre særlig rekkefølgen, hvem som kan forbedre løsningen, og om lederen velger riktig avsender.",
      "client_intro": "Et interessentkart gir oversikt, men ikke nødvendigvis handling. Denne øvelsen hjelper deg å velge hvem som bør involveres først, hvorfor og med hvilken konkret henvendelse.",
      "suggested_coach_note": "Ta utgangspunkt i interessentkartet ditt og velg de tre aktørene som er viktigst for saken akkurat nå.",
      "default_context_types": ["focus_area", "session", "experiment"],
      "content_json": [
        { "type": "intro", "content": "Bruk det eksisterende interessentkartet. Målet her er å velge handling, rekkefølge og riktig form for involvering." },
        { "type": "text", "heading": "1. Prioriter tre interessenter", "content": "Velg aktørene som er viktigst for sakens kvalitet eller gjennomføring nå, ikke nødvendigvis dem med høyest formell posisjon." },
        { "type": "worksheet", "fields": ["Interessent 1", "Interessent 2", "Interessent 3", "Hvorfor er disse tre viktigst nå?"] },
        { "type": "text", "heading": "2. Velg tilnærming", "content": "Vurder ønsket bidrag, interesser, mulige bekymringer og hva du fortsatt trenger å forstå for hver aktør." },
        { "type": "worksheet", "fields": ["Hva ønsker du fra hver interessent?", "Hva kan saken bety for deres mål eller risiko?", "Skal de informeres, konsulteres, involveres i utforming eller bes om en beslutning?", "Hvem er den mest troverdige avsenderen?"] },
        { "type": "text", "heading": "3. Bestem rekkefølgen", "content": "Noen aktører bør bidra før løsningen er ferdig. Andre trenger først å se hvordan sentrale spørsmål er håndtert." },
        { "type": "worksheet", "fields": ["Hvem involveres først, og hvorfor?", "Hva er første konkrete henvendelse?", "Hva må du lære før neste interessent kontaktes?", "Når skal planen vurderes på nytt?"] },
        { "type": "reflection_questions", "heading": "Tenk gjennom", "questions": ["Hvem står sent i planen, men burde vært involvert tidlig?", "Hvem kan forbedre løsningen, ikke bare støtte den?", "Hvor kan samme budskap få ulik virkning fordi interessene er forskjellige?"] }
      ],
      "reflection_prompts": [],
      "next_step_prompt": "Send den første henvendelsen og bruk det du lærer til å justere resten av planen.",
      "basis": "Forskning på påvirkningsmål, relasjonsretning og valg av påvirkningstaktikk. Yukl og Falbe (1990); Yukl, Guinan og Sottolano (1995)."
    },
    {
      "title": "Deleger for utvikling, ikke bare avlastning",
      "slug": "deleger-for-utvikling-ikke-bare-avlastning",
      "type": "worksheet",
      "phase": "experiment",
      "estimated_duration": 15,
      "difficulty": "medium",
      "intended_outcome": "Avklare leveranse, utviklingsmål, beslutningsrom, risikogrenser og støtte uten at lederen tar tilbake eierskapet.",
      "best_used_when": ["en medarbeider er klar for mer ansvar", "lederen vil bruke en reell oppgave som utviklingsarena", "delegering ofte blir enten detaljstyrt eller for løst fulgt opp"],
      "not_for": ["medarbeideren mangler nødvendig støtte eller kapasitet", "kritiske oppgaver der feilrisikoen ikke kan håndteres", "utviklingshensyn brukes til å legitimere urimelig arbeidsbelastning"],
      "coach_guidance": "Start med en oppgave som uansett må leveres. Undersøk om utviklingsstrekket er relevant for medarbeideren, og hjelp lederen å skille støtte fra overtakelse. Tydelige grenser er en forutsetning for reelt handlingsrom.",
      "client_intro": "Delegering kan både flytte ansvar og utvikle kapasitet. Denne øvelsen hjelper deg å gi en reell oppgave med tydelig resultat, handlingsrom, støtte og læring.",
      "suggested_coach_note": "Bruk denne på én konkret oppgave som kan gi en medarbeider relevant strekk, ikke bare mer arbeid.",
      "default_context_types": ["focus_area", "experiment", "session"],
      "content_json": [
        { "type": "intro", "content": "En utviklende delegering må fortsatt være en forsvarlig leveranse. Utfordringen skal komme fra relevant ansvar og læring, ikke fra uklare forventninger eller manglende støtte." },
        { "type": "model_cards", "heading": "Fire deler som må henge sammen", "cards": [{ "title": "Leveranse", "body": "Hva skal være oppnådd, og hvorfor betyr det noe?" }, { "title": "Læring", "body": "Hvilken relevant kapasitet kan medarbeideren utvikle gjennom oppgaven?" }, { "title": "Handlingsrom", "body": "Hva kan medarbeideren beslutte selv, og hva må forankres?" }, { "title": "Oppfølging", "body": "Når trengs støtte, kontrollpunkt og læringssamtale?" }] },
        { "type": "text", "heading": "1. Avklar oppgaven", "content": "Beskriv resultatet tydelig nok til at medarbeideren kan velge fremgangsmåte innenfor avtalte rammer." },
        { "type": "worksheet", "fields": ["Hvilken leveranse skal delegeres?", "Hvorfor er den viktig?", "Hvilket utviklingsbehov kan oppgaven trene?", "Hvordan vet dere at leveransen er god nok?"] },
        { "type": "text", "heading": "2. Avklar handlingsrom og risiko", "content": "Bestem hva medarbeideren eier, hva som skal forankres, og når lederen må kobles inn." },
        { "type": "worksheet", "fields": ["Hva kan medarbeideren beslutte selv?", "Hva skal forankres?", "Hvilke feil kan medarbeideren få lov til å gjøre?", "Hvilken risiko krever at du kobles inn?"] },
        { "type": "text", "heading": "3. Avtal støtte og oppfølging", "content": "Spør hvilken støtte medarbeideren ønsker før du tilbyr løsningene dine." },
        { "type": "worksheet", "fields": ["Hvilken støtte ønsker medarbeideren?", "Når er første kontrollpunkt?", "Hva skal dere snakke om når dere vurderer læringen?", "Hva vil du sannsynligvis bli fristet til å overta?"] },
        { "type": "reflection_questions", "heading": "Tenk gjennom", "questions": ["Er oppgaven utfordrende av riktig grunn, eller bare dårlig avgrenset?", "Er arbeidsbelastningen rimelig?", "Hvordan vil du støtte uten å bestemme fremgangsmåten?"] }
      ],
      "reflection_prompts": [],
      "next_step_prompt": "Ta delegeringssamtalen og be medarbeideren gjengi resultat, handlingsrom og første steg med egne ord.",
      "basis": "Forskning på utviklingskomponenter i lederjobber og læring gjennom utfordrende arbeidsoppgaver. McCauley, Ruderman, Ohlott og Morrow (1994)."
    },
    {
      "title": "Skap eierskap uten å overta",
      "slug": "skap-eierskap-uten-a-overta",
      "type": "exercise",
      "phase": "experiment",
      "estimated_duration": 12,
      "difficulty": "easy",
      "intended_outcome": "Beholde tydelige rammer samtidig som medarbeideren eier vurdering, anbefaling og neste steg.",
      "best_used_when": ["lederen går raskt til løsning når medarbeidere kommer med problemer", "ansvar glir tilbake til lederen i samtalen", "medarbeidere venter på svar fremfor å utvikle egne vurderinger"],
      "not_for": ["situasjoner med vesentlig risiko eller manglende forutsetninger", "bruk for å trekke seg unna lederansvar", "uklare roller eller beslutningsmandater som må avklares først"],
      "coach_guidance": "Se etter lederens hjelpsomhet som overtakelsesmønster. Samtidig må du beskytte tydelig retning, struktur og ansvar. Autonomi betyr ikke at medarbeideren overlates til seg selv.",
      "client_intro": "Når du løser problemer raskt for andre, kan du samtidig gjøre dem mer avhengige av deg. Denne øvelsen hjelper deg å støtte uten å ta tilbake vurderingen og ansvaret.",
      "suggested_coach_note": "Velg en kommende samtale der du vanligvis ville gått raskt til løsning. Øv på å avklare rammene og la medarbeideren eie vurderingen.",
      "default_context_types": ["focus_area", "experiment", "reflection"],
      "content_json": [
        { "type": "intro", "content": "Eierskap krever både handlingsrom og tydelige rammer. Din oppgave er å avklare retning, risiko og beslutningsmyndighet uten automatisk å bli den som løser problemet." },
        { "type": "callout", "tone": "note", "heading": "Hold fast på lederansvaret", "content": "Du skal fortsatt sette retning, avklare ansvar og gripe inn ved vesentlig risiko. Å ikke overta er noe annet enn å trekke seg unna." },
        { "type": "text", "heading": "1. Velg situasjonen", "content": "Velg en kommende samtale der noen sannsynligvis vil be deg om svar, løsning eller beslutning." },
        { "type": "worksheet", "fields": ["Hvilken situasjon gjelder det?", "Hva pleier du å gjøre som flytter eierskapet til deg?", "Hva er fast: ønsket resultat, rammer, risiko og beslutningsmyndighet?"] },
        { "type": "text", "heading": "2. Forbered spørsmålene", "content": "Spør etter vurdering og anbefaling før du tilbyr din egen løsning." },
        { "type": "worksheet", "fields": ["Hva har du allerede vurdert?", "Hvilke muligheter ser du?", "Hva anbefaler du, og hvorfor?", "Hvilken støtte trenger du fra meg?"] },
        { "type": "text", "heading": "3. Avslutt med tydelig eierskap", "content": "Samtalen skal ende med en navngitt eier, et konkret neste steg og et avtalt tidspunkt for oppfølging." },
        { "type": "worksheet", "fields": ["Hvem eier neste steg?", "Hva skal gjøres?", "Når følger dere opp?", "Hva skal du passe på at du ikke tar tilbake?"] },
        { "type": "reflection_questions", "heading": "Tenk gjennom", "questions": ["Når blir din hjelpsomhet en form for overtakelse?", "Hva gjør det vanskelig å vente på medarbeiderens vurdering?", "Hvilken støtte bygger kompetanse fremfor avhengighet?"] }
      ],
      "reflection_prompts": [],
      "next_step_prompt": "Prøv spørsmålene i én reell samtale og observer hvem som formulerer anbefalingen og neste steg.",
      "basis": "Selvbestemmelsesteori med vekt på støtte til autonomi, kompetanse og tilhørighet. Ryan og Deci (2000)."
    },
    {
      "title": "Når en styrke brukes for mye",
      "slug": "nar-en-styrke-brukes-for-mye",
      "type": "reflection",
      "phase": "adjustment",
      "estimated_duration": 15,
      "difficulty": "medium",
      "intended_outcome": "Identifisere overbruk av en styrke, velge en komplementær atferd og prøve en bedre dosering i en konkret situasjon.",
      "best_used_when": ["lederen får gjentatt feedback på en atferd som også er nyttig", "en styrke får svak effekt i bestemte situasjoner", "intensjonen er god, men virkningen blir for sterk eller ensidig"],
      "not_for": ["bruk for å gjøre alle styrker til skjulte svakheter", "personlighetsdiagnostikk eller faste merkelapper", "situasjoner der problemet er manglende ferdighet fremfor overbruk"],
      "coach_guidance": "Hold arbeidet situasjonsbestemt. Ikke be lederen dempe styrken generelt. Finn konteksten der intensitet, hyppighet eller varighet blir for stor, og velg en konkret motvekt.",
      "client_intro": "En styrke kan miste effekt når den brukes for sterkt, for ofte eller i feil situasjon. Denne øvelsen hjelper deg å beholde verdien og justere doseringen.",
      "suggested_coach_note": "Velg én styrke du har fått både positiv og krevende feedback på. Bruk en konkret situasjon, ikke en generell beskrivelse av deg selv.",
      "default_context_types": ["focus_area", "reflection", "experiment"],
      "content_json": [
        { "type": "intro", "content": "Målet er ikke å gjøre deg mindre tydelig, handlekraftig, grundig eller omsorgsfull. Målet er å bruke styrken slik situasjonen faktisk trenger." },
        { "type": "model_cards", "heading": "Se etter doseringen", "cards": [{ "title": "Underbruk", "body": "Styrken får for liten plass til å gi den virkningen situasjonen trenger." }, { "title": "God bruk", "body": "Styrken brukes med en intensitet og timing som støtter oppgaven og relasjonen." }, { "title": "Overbruk", "body": "Styrken dominerer så mye at den fortrenger annen nødvendig atferd." }] },
        { "type": "text", "heading": "1. Beskriv styrken", "content": "Navngi styrken som en atferd du kan justere, ikke som en fast identitet." },
        { "type": "worksheet", "fields": ["Hvilken styrke eller nyttig atferd gjelder det?", "Når gir den tydelig verdi?", "Hva ser andre når du bruker den godt?"] },
        { "type": "text", "heading": "2. Finn overbrukssignalet", "content": "Se etter hva som skjer når styrken blir for sterk, for hyppig eller varer for lenge." },
        { "type": "worksheet", "fields": ["Hva kan andre observere når styrken tipper over?", "Hvilken kostnad får det for oppgave, relasjon eller læring?", "Hvem merker overbruken før du gjør det selv?", "Hva er ditt tidligste signal?"] },
        { "type": "text", "heading": "3. Velg en motvekt", "content": "Finn en komplementær atferd som skal få litt mer plass, uten at du legger bort styrken." },
        { "type": "worksheet", "fields": ["Hvilken atferd trenger mer plass?", "I hvilken kommende situasjon skal du justere doseringen?", "Hva skal du konkret gjøre annerledes?", "Hva vil være et tegn på bedre effekt?"] },
        { "type": "reflection_questions", "heading": "Tenk gjennom", "questions": ["Hva gjør at du skrur styrken opp i denne typen situasjon?", "Hva frykter du kan skje dersom du bruker mindre av den?", "Hvordan kan du beholde verdien uten å bruke styrken automatisk?"] }
      ],
      "reflection_prompts": [],
      "next_step_prompt": "Prøv den justerte doseringen i én situasjon og be én person beskrive hva de la merke til.",
      "basis": "Forskning på lederstyrker, overbruk og ubalansert lederatferd. Kaiser og Overfield (2011)."
    },
    {
      "title": "Fra forsvar til nysgjerrighet",
      "slug": "fra-forsvar-til-nysgjerrighet",
      "type": "reflection",
      "phase": "adjustment",
      "estimated_duration": 15,
      "difficulty": "medium",
      "intended_outcome": "Oppdage ett tidlig forsvarsmønster og prøve en konkret pause- og spørsmålsrespons i en krevende situasjon.",
      "best_used_when": ["kritikk eller usikkerhet utløser raske forklaringer eller avvisning", "lederen blir taus, detaljstyrende eller opptatt av å vinne", "andre holder tilbake informasjon når lederen blir utfordret"],
      "not_for": ["legitime grenser eller faglig uenighet gjøres til et personlig problem", "reaksjoner på reell utrygghet eller skadelig atferd", "alvorlig konflikt som krever annen faglig eller formell håndtering"],
      "coach_guidance": "Normaliser at forsvar kan oppstå under press, men hold lederen ansvarlig for virkningen. Unngå karakterforklaringer. Arbeid med det tidligste observerbare signalet og én konkret respons som øker informasjonsinnhentingen.",
      "client_intro": "Når du opplever kritikk, usikkerhet eller tap av kontroll, kan oppmerksomheten snevres inn. Denne øvelsen hjelper deg å oppdage reaksjonen tidligere og holde dialogen åpen litt lenger.",
      "suggested_coach_note": "Bruk denne på én konkret situasjon der du gikk raskt i forklaring, avvisning, kontroll eller taushet da du ble utfordret.",
      "default_context_types": ["reflection", "experiment", "session"],
      "content_json": [
        { "type": "intro", "content": "Forsvar er ofte et forsøk på å beskytte noe som oppleves truet. Utviklingsarbeidet starter med å oppdage reaksjonen før den bestemmer hele samtalen." },
        { "type": "callout", "tone": "note", "heading": "Nysgjerrighet er ikke ettergivenhet", "content": "Du kan holde fast på en grense eller være faglig uenig og samtidig undersøke hva den andre ser. Målet er bedre informasjon, ikke automatisk enighet." },
        { "type": "text", "heading": "1. Gå tilbake til situasjonen", "content": "Velg en konkret hendelse der du ble utfordret, usikker eller opplevde tap av kontroll." },
        { "type": "worksheet", "fields": ["Hva skjedde?", "Hva var ditt første kroppslige, tankemessige eller atferdsmessige signal?", "Hva forsøkte du å beskytte: kontroll, status, selvbilde, tempo eller noe annet?", "Hva gjorde du deretter?"] },
        { "type": "text", "heading": "2. Finn informasjonen som forsvant", "content": "Beskriv hva du sluttet å høre, spørre om eller vurdere da forsvaret tok mer plass." },
        { "type": "worksheet", "fields": ["Hvilken informasjon tok du ikke inn?", "Hva kan ha skjedd med den andres vilje til å si mer?", "Hvilken del av kritikken kan være nyttig selv om du er uenig i resten?"] },
        { "type": "text", "heading": "3. Forbered en annen respons", "content": "Velg en kort pausehandling og ett ekte spørsmål som hjelper deg å forstå før du svarer." },
        { "type": "worksheet", "fields": ["Mitt tidlige stoppsignal", "Min pausehandling", "Spørsmålet jeg vil stille", "Hva vil være et tegn på at jeg forble åpen lenger?"] },
        { "type": "reflection_questions", "heading": "Tenk gjennom", "questions": ["Hva gjør du som kan få andre til å holde tilbake informasjon?", "Hva blir vanskelig ved å vente med forklaringen din?", "Hvordan kan du undersøke antakelsen din uten å gi opp eget standpunkt?"] }
      ],
      "reflection_prompts": [],
      "next_step_prompt": "Bruk pausehandlingen og spørsmålet i én krevende samtale. Noter etterpå hvilken ny informasjon du fikk.",
      "basis": "Forskning på trussel og rigiditet i organisasjoner samt defensive rutiner. Staw, Sandelands og Dutton (1981); Argyris (1990)."
    }
  ]$$::jsonb) as resource(
    title text,
    slug text,
    type text,
    phase text,
    estimated_duration integer,
    difficulty text,
    intended_outcome text,
    best_used_when jsonb,
    not_for jsonb,
    coach_guidance text,
    client_intro text,
    suggested_coach_note text,
    default_context_types jsonb,
    content_json jsonb,
    reflection_prompts jsonb,
    next_step_prompt text,
    basis text
  )
)
insert into public.resources (
  title,
  slug,
  summary,
  type,
  format,
  phase,
  visibility,
  status,
  review_status,
  language,
  estimated_duration,
  difficulty,
  intended_outcome,
  best_used_when,
  not_for,
  coach_guidance,
  client_intro,
  suggested_coach_note,
  default_context_types,
  content_json,
  reflection_prompts,
  next_step_prompt,
  basis,
  reviewed_by,
  last_reviewed_at,
  archived_at
)
select
  title,
  slug,
  client_intro,
  type,
  'native',
  phase,
  'client_assignable',
  'draft',
  'draft',
  'no',
  estimated_duration,
  difficulty,
  intended_outcome,
  best_used_when,
  not_for,
  coach_guidance,
  client_intro,
  suggested_coach_note,
  default_context_types,
  content_json,
  reflection_prompts,
  next_step_prompt,
  basis,
  null,
  null,
  null
from seed_resources
on conflict (slug) do update
set
  title = excluded.title,
  summary = excluded.summary,
  type = excluded.type,
  format = excluded.format,
  phase = excluded.phase,
  visibility = excluded.visibility,
  status = excluded.status,
  review_status = excluded.review_status,
  language = excluded.language,
  estimated_duration = excluded.estimated_duration,
  difficulty = excluded.difficulty,
  intended_outcome = excluded.intended_outcome,
  best_used_when = excluded.best_used_when,
  not_for = excluded.not_for,
  coach_guidance = excluded.coach_guidance,
  client_intro = excluded.client_intro,
  suggested_coach_note = excluded.suggested_coach_note,
  default_context_types = excluded.default_context_types,
  content_json = excluded.content_json,
  reflection_prompts = excluded.reflection_prompts,
  next_step_prompt = excluded.next_step_prompt,
  basis = excluded.basis,
  reviewed_by = null,
  last_reviewed_at = null,
  archived_at = null,
  updated_at = now();

with seed_slugs as (
  select jsonb_array_elements_text($$[
    "fra-strategi-til-konkret-lederpraksis",
    "forsta-motstand-for-du-leder-endring",
    "definer-problemet-for-du-velger-losning",
    "test-antakelsene-bak-beslutningen",
    "hva-bygger-og-bryter-ned-tillit",
    "gjenopprett-tillit-etter-et-brudd",
    "skap-gjennomslag-uten-formell-myndighet",
    "fra-interessentkart-til-pavirkningsgrep",
    "deleger-for-utvikling-ikke-bare-avlastning",
    "skap-eierskap-uten-a-overta",
    "nar-en-styrke-brukes-for-mye",
    "fra-forsvar-til-nysgjerrighet"
  ]$$::jsonb) as slug
)
delete from public.resource_tags rt
using public.resources r, seed_slugs s
where rt.resource_id = r.id
  and r.slug = s.slug;

with seed_tags as (
  select *
  from jsonb_to_recordset($$[
    { "slug": "fra-strategi-til-konkret-lederpraksis", "tags": ["area:strategy_business_change", "strategi", "lederatferd", "gjennomføring", "prioritering"] },
    { "slug": "forsta-motstand-for-du-leder-endring", "tags": ["area:strategy_business_change", "endring", "motstand", "involvering", "observasjon"] },
    { "slug": "definer-problemet-for-du-velger-losning", "tags": ["area:execution_decisions", "problemløsning", "problemforståelse", "beslutninger", "analyse"] },
    { "slug": "test-antakelsene-bak-beslutningen", "tags": ["area:execution_decisions", "beslutninger", "antakelser", "risiko", "kritisk tenkning"] },
    { "slug": "hva-bygger-og-bryter-ned-tillit", "tags": ["area:relationships_influence", "tillit", "troverdighet", "relasjoner", "lederatferd"] },
    { "slug": "gjenopprett-tillit-etter-et-brudd", "tags": ["area:relationships_influence", "tillit", "tillitsbrudd", "ansvar", "relasjoner"] },
    { "slug": "skap-gjennomslag-uten-formell-myndighet", "tags": ["area:relationships_influence", "påvirkning", "gjennomslag", "samarbeid", "relasjoner"] },
    { "slug": "fra-interessentkart-til-pavirkningsgrep", "tags": ["area:relationships_influence", "interessenter", "påvirkning", "involvering", "rekkefølge"] },
    { "slug": "deleger-for-utvikling-ikke-bare-avlastning", "tags": ["area:team_people", "delegering", "utvikling", "ansvar", "medarbeidere"] },
    { "slug": "skap-eierskap-uten-a-overta", "tags": ["area:team_people", "eierskap", "autonomi", "coachende ledelse", "medarbeidere"] },
    { "slug": "nar-en-styrke-brukes-for-mye", "tags": ["area:derailer", "styrker", "overbruk", "selvinnsikt", "lederatferd"] },
    { "slug": "fra-forsvar-til-nysgjerrighet", "tags": ["area:derailer", "forsvar", "nysgjerrighet", "feedback", "selvinnsikt"] }
  ]$$::jsonb) as tag_group(slug text, tags jsonb)
)
insert into public.resource_tags (resource_id, tag)
select r.id, tag_value.tag
from seed_tags st
join public.resources r on r.slug = st.slug
cross join lateral jsonb_array_elements_text(st.tags) as tag_value(tag)
on conflict (resource_id, tag) do nothing;
